inherit_from:
  - .rubocop/bundler.yml
  - .rubocop/gemspec.yml
  - .rubocop/layout.yml
  - .rubocop/lint.yml
  - .rubocop/metrics.yml
  - .rubocop/naming.yml
  - .rubocop/rspec.yml
  - .rubocop/security.yml
  - .rubocop/style.yml

require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 3.3
  Exclude:
    - bin/**/*
    - vendor/**/*
    - spec/spec_helper.rb
    - "*.gemspec"

Bundler/GemComment:
  Exclude:
    - 'Gemfile'

Naming/FileName:
  Exclude:
    - 'lib/cerise-rubocop.rb'

Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
    - Metrics/MethodLength

Style/DocumentationMethod:
  Exclude:
    - 'spec/**/*'
